* Questions
  
* Alpha (Demoable/guided)
  * Space branding of main app - contentious
  * Invoice details page.
  * Member portal design changes (design coming?)

* Beta (5-10 early adopters)

  * Scheduled invoices (subsciptions auto generate)
    * Scheduled payments (auto payment for subscriptions)
    * Email payment receipts - Mailer done, will call when doing subscription payments
      * Perhaps it should still send the email when adding any kind of payment?!?

  * Make use of timezone?  - Maybe only needed in the scheduled invoices and payments scripts

  * Possibly add tax rate to line_items (and present in UI as the field to edit, compute on the back end)

  * Deleting a draft invoice needs to delete all children (payments and/or credit notes)

* 2.0 (MVP, ship in January-february time frame, available to all, for money)
  * Change member password
  * Member password recovery
    * Can also/do instead password reset on admin site (would resend invite basically)

* 2.1

* 2.2

* Backlog
  * Space Branding for member portal
  * Improve display of errors on fields for devise forms.
  * Add "due in" to issue date column on invoice list?
  * Add evil icons (rails plugin, etc) or are we going to use pngs generated from AI file?
    * Looks like they're making a pass to add more icons!  Could get full set of needed very soon.
  * Events/Notifcations (Activity Tab in New navigation)
  * Maybe add Tags to members to allow arbitrary groupings
  * Add 'Social' Signup/Login for Member portal (FB, Twitter, G+)?
  * Add team support

  * Attendance tracking (check in, out)
  * Attendance tracking API (remote systems updating)
  * Attendance tracking self checking kiosk mode (use attendance tracking api?)
  * Attendance analytics

  * Vanity analytics (# members, etc - probably 'built-in' to each screen)

  * Punch cards

  * Braintree payment gateway
  * Paypal payments (offsite)

  * API Server side
    * Api authentication
    * Api implementation (Per space)
      * members
      * billing
      * member auth
  * API Client side (restful, ruby, golang? python?, etc?)



so, my thoughts on once its sent
label by invoice number changes to sent
edit invoice button goes away
more actions button goes away
replaced by Add Credit Note
Send invoice becomes Send Reminder? at some point
until then, it can go away too
so only options are add credit note and record payment
or is there another action once its sent?
Matt • 1 min
yeah until paid
no
1 min
Vince Hodges
Matt Farley
ok
or maybe instead of removing buttons, we disable them
Matt • 1 min
if you prefer
Now
Vince Hodges
Matt Farley
not sure
oh, and one more thing
when invoice is paid
all buttons are disabled
record payment is removed
Matt • Now
ok
Now
Vince Hodges
