#
# These are all test/development codes.
#
STRIPE_API_KEY: sk_test_S6iKi7H6EFHvAScbSPG7k8WG
STRIPE_PUBLISHABLE_KEY: pk_test_8CiyjZmBTeEdYbM9nmDFgd04

# For OAuth
STRIPE_CLIENT_ID: ca_2fT1A6ea7MGAPMkXISnq7qS2zMUi030P  
